name: Setup & Install Node.js

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: npm

    - name: Install Node.js dependencies
      shell: bash
      run: npm ci
