name: CI - Affected

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Build & Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set SHAs for affected command
        uses: nrwl/nx-set-shas@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Install Cypress (cached)
        run: npx cypress install # Test comment

      - name: Setup .NET SDK
        uses: ./.github/actions/setup-dotnet

      - name: Run affected targets
        run: |
          npx nx affected -t lint test build e2e --verbose
