name: Deploy React App (Nx Workspace)

on:
  push:
    branches:
      - main
    paths:
      - 'react/apps/transactions/**'
      - 'react/libs/**'
      - 'package.json'
      - 'package-lock.json'
      - 'nx.json'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Nx affected

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Build React App
        run: npx nx build react-transactions-app --prod

      - name: Deploy to Production # Example: Netlify
        uses: netlify/actions/cli@master # Replace with your deployment method
        with:
          args: deploy --prod --dir=dist/react/apps/transactions
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # Alternative deployment examples:

      # Example: Deploy to AWS S3 + CloudFront
      # - name: Deploy to S3
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: your-aws-region
      # - name: Sync to S3 bucket
      #   run: aws s3 sync dist/react/apps/transactions s3://your-s3-bucket --delete

      # - name: Invalidate CloudFront cache
      #   run: aws cloudfront create-invalidation --distribution-id your-cloudfront-distribution-id --paths "/*"

      # Example: Deploy to Firebase Hosting
      # - name: Deploy to Firebase Hosting
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --only hosting
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Example: Deploy to Vercel
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     working-directory: ./dist/react/apps/transactions
