name: "CI/CD React Deploy"

on:
  push:
    branches:
      - main

jobs:
  # 1. Build the React application(s) and upload the artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set SHAs for affected command
        uses: nrwl/nx-set-shas@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Build React App
        run: npx nx affected -t build --exclude='*,!tag:lang:react'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/react/apps/

  # 2. Deploy to Dev environment
  deploy-dev:
    name: "Deploy to Dev"
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Deploy to Dev
        run: |
          echo "Starting deployment to DEV..."

  # 3. Deploy to UAT, only if Dev succeeded
  deploy-uat:
    name: "Deploy to UAT"
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Deploy to UAT
        run: |
          echo "Starting deployment to UAT..."

  # 4. Deploy to PPR, only if UAT succeeded
  deploy-ppr:
    name: "Deploy to PPR"
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: ppr
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Deploy to PPR
        run: |
          echo "Starting deployment to PPR..."

  # 5. Deploy to Production, only if PPR succeeded
  deploy-prd:
    name: "Deploy to Production"
    needs: deploy-ppr
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Deploy to Production
        run: |
          echo "Starting deployment to PRODUCTION..."
