# ./.github/workflows/npm-publish.yml
name: Publish NPM Packages

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set SHAs for affected command
        uses: nrwl/nx-set-shas@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Publish packages
        run: npx nx affected -t nx-release-publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
