name: Publish .NET Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set SHAs for affected command
        uses: nrwl/nx-set-shas@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Setup .NET SDK
        uses: ./.github/actions/setup-dotnet

      - name: Build .NET libraries
        run: |
          npx nx affected -t build --exclude='*,!tag:lang:dotnet' --verbose

      - name: Pack NuGet package
        run: npx nx affected --target=pack --verbose

      - name: Publish to NuGet
        run: npx nx affected --target=publish --args="--source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}"
