name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for last-release

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/push-based/multilanguage-monorepo.git

      - name: Run Nx Version
        run: npx nx affected --target=version --base=last-release --parallel=1

      - name: Create and Push Tag
        run: |
          git tag -f last-release
          git push origin last-release --force -o ci.skip
